apiVersion: apps/v1
kind: Deployment
metadata:
  name: persistence-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: persistence-worker
  template:
    metadata:
      labels:
        app: persistence-worker
    spec:
      volumes:
        - name: dshm
          emptyDir: { medium: Memory, sizeLimit: 256Mi }
      containers:
        - name: worker
          image: exchange-engine-persistence-worker:v-pure-final
          volumeMounts:
            - mountPath: /dev/shm
              name: dshm
          env:
            - name: MAIN_CLASS
              value: "com.exchange.PersistenceWorkerKt"
            - name: ARGS
              value: "--embedded-driver"
            - name: DB_HOST
              valueFrom: { configMapKeyRef: { name: exchange-config, key: DB_HOST } }
            - name: AERON_PUB_CHANNEL
              value: "aeron:udp?endpoint=localhost:40123" # Not used by worker
            - name: AERON_SUB_CHANNEL
              valueFrom: { configMapKeyRef: { name: exchange-config, key: SUB_LISTEN_OME } }
